spring:
  datasource:
    driver-class-name:  com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/root?serverTimezone=GMT%2B8
    username: root
    password: 1314789
  thymeleaf:
    mode: HTML5
